### ISSUE TITLE
Goal tolerance vs GoalGuidedMultivariateGaussian

### ISSUE THREAD

**Issue by simonschmeisser** [ros-industrial/stomp_ros#25]
I noticed that Stomp often fails to find a valid solution for me if using GoalGuidedMultivariateGaussian. Looking at the intermediates via
```
noisy_filters:
     - [...]
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.02
        rgb: [0, 255, 0]
        marker_array_topic: stomp_trajectories
        marker_namespace: noisy
```

I observe that the goals (visualized as spheres in rviz) are quite far apart and do not seem to obey tolerances requested from MoveIt. Switching to `NormalDIstributionSampling` as noise generator works fine however.

@mamoll maybe this is the root of your issues as well?
